### ISSUE TITLE
Invalid requirements

### ISSUE THREAD

**Issue by javadnikbakht** [yasinrezaei/PersonalBlog#1]
I know this is a personal repository probably for your blog but when you publish as an open source code it's better it works normally and Ok without adding anything to project for other people use.
In line 79 of your `requirements.txt` file There is a shit Windows directory address that must be removed from the requirements file to users can install them successfully.

**Comment by javadnikbakht** [comment]
Also what is that package in line 155? I think it should be removed too.

**Comment by yasinrezaei** [comment]
> I know this is a personal repository probably for your blog but when you publish as an open source code it's better it works normally and Ok without adding anything to project for other people use.
> In line 79 of your `requirements.txt` file There is a shit Windows directory address that must be removed from the requirements file to users can install them successfully.

-------------------------------------------
Thanks for your comment

I am not at a high level of Django framework and I created this blog to get acquainted with Django space :)
I edited the two lines you mentioned.
